services:
  - type: web
    name: bps-project
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bps_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bps_project.settings
